/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinRouteImport } from './routes/win'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as MusicRouteImport } from './routes/music'
import { Route as ListenRouteImport } from './routes/listen'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShowsSlugRouteImport } from './routes/shows.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const WinRoute = WinRouteImport.update({
  id: '/win',
  path: '/win',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenRoute = ListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsSlugRoute = ShowsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShowsRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/listen': typeof ListenRoute
  '/music': typeof MusicRoute
  '/photos': typeof PhotosRoute
  '/shows': typeof ShowsRouteWithChildren
  '/stories': typeof StoriesRoute
  '/videos': typeof VideosRoute
  '/win': typeof WinRoute
  '/admin/login': typeof AdminLoginRoute
  '/shows/$slug': typeof ShowsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/listen': typeof ListenRoute
  '/music': typeof MusicRoute
  '/photos': typeof PhotosRoute
  '/shows': typeof ShowsRouteWithChildren
  '/stories': typeof StoriesRoute
  '/videos': typeof VideosRoute
  '/win': typeof WinRoute
  '/admin/login': typeof AdminLoginRoute
  '/shows/$slug': typeof ShowsSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/listen': typeof ListenRoute
  '/music': typeof MusicRoute
  '/photos': typeof PhotosRoute
  '/shows': typeof ShowsRouteWithChildren
  '/stories': typeof StoriesRoute
  '/videos': typeof VideosRoute
  '/win': typeof WinRoute
  '/admin/login': typeof AdminLoginRoute
  '/shows/$slug': typeof ShowsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/listen'
    | '/music'
    | '/photos'
    | '/shows'
    | '/stories'
    | '/videos'
    | '/win'
    | '/admin/login'
    | '/shows/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/listen'
    | '/music'
    | '/photos'
    | '/shows'
    | '/stories'
    | '/videos'
    | '/win'
    | '/admin/login'
    | '/shows/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/listen'
    | '/music'
    | '/photos'
    | '/shows'
    | '/stories'
    | '/videos'
    | '/win'
    | '/admin/login'
    | '/shows/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ListenRoute: typeof ListenRoute
  MusicRoute: typeof MusicRoute
  PhotosRoute: typeof PhotosRoute
  ShowsRoute: typeof ShowsRouteWithChildren
  StoriesRoute: typeof StoriesRoute
  VideosRoute: typeof VideosRoute
  WinRoute: typeof WinRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/win': {
      id: '/win'
      path: '/win'
      fullPath: '/win'
      preLoaderRoute: typeof WinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen': {
      id: '/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof ListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$slug': {
      id: '/shows/$slug'
      path: '/$slug'
      fullPath: '/shows/$slug'
      preLoaderRoute: typeof ShowsSlugRouteImport
      parentRoute: typeof ShowsRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShowsRouteChildren {
  ShowsSlugRoute: typeof ShowsSlugRoute
}

const ShowsRouteChildren: ShowsRouteChildren = {
  ShowsSlugRoute: ShowsSlugRoute,
}

const ShowsRouteWithChildren = ShowsRoute._addFileChildren(ShowsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ListenRoute: ListenRoute,
  MusicRoute: MusicRoute,
  PhotosRoute: PhotosRoute,
  ShowsRoute: ShowsRouteWithChildren,
  StoriesRoute: StoriesRoute,
  VideosRoute: VideosRoute,
  WinRoute: WinRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
